// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPICore.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWebAPICore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220222123129_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyWebAPICore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1950, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "cloehopper@school.com",
                            Image = "cloehopper",
                            Name = "Cloe Hopper"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1955, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "davidremnick@school.com",
                            Image = "davidremnick",
                            Name = "David Remnick"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1967, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "joannakavena@gmail.com",
                            Image = "joannakavena",
                            Name = "Joanna Kavena"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1912, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "johncheever@school.com",
                            Image = "johncheever",
                            Name = "John Cheever"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1980, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "joshuacohen@school.com",
                            Image = "joshuacohen",
                            Name = "Joshua Cohen"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1971, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "patrickness@school.com",
                            Image = "patrickness",
                            Name = "Patrick Ness"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1975, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "rebeccaswift@school.com",
                            Image = "rebeccaswift",
                            Name = "Rebecca Swift"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1979, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "sarahperry@school.com",
                            Image = "sarahperry",
                            Name = "Sarah Perry"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1948, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "simonmawer@school.com",
                            Image = "simonmawer",
                            Name = "Simon Mawer"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1960, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "tomwinton@school.com",
                            Image = "tomwinton",
                            Name = "Tom Winton"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.AuthorBook", b =>
                {
                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("BookId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("AuthorBooks");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 7
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 11
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 24
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 28
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 9
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 11
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 19
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 29
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 4
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 12
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 21
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 26
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 15
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 22
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 27
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 2
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 8
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 10
                        },
                        new
                        {
                            AuthorId = 6,
                            BookId = 17
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 1
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 5
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 23
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 30
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 3
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 13
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 14
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 17
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 18
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 25
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 29
                        },
                        new
                        {
                            AuthorId = 10,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 10,
                            BookId = 20
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "bjsf",
                            Pages = 171,
                            Price = 79.950000000000003,
                            PublisherId = 1,
                            Title = "Bloated JabbaScript Frameworks"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "bta",
                            Pages = 158,
                            Price = 79.950000000000003,
                            PublisherId = 2,
                            Title = "Blaming the Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "btog",
                            Pages = 111,
                            Price = 69.950000000000003,
                            PublisherId = 3,
                            Title = "Blame the Other Guy"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "btu",
                            Pages = 152,
                            Price = 69.950000000000003,
                            PublisherId = 4,
                            Title = "Blaming the User"
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "coft",
                            Pages = 166,
                            Price = 69.950000000000003,
                            PublisherId = 5,
                            Title = "Commenting Out Failed Tests"
                        },
                        new
                        {
                            Id = 6,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "cpso",
                            Pages = 159,
                            Price = 69.950000000000003,
                            PublisherId = 5,
                            Title = "Copying and Pasting from Stack Overflow"
                        },
                        new
                        {
                            Id = 7,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "cswh",
                            Pages = 129,
                            Price = 59.950000000000003,
                            PublisherId = 4,
                            Title = "Changing Stuff and Seeing What Happens"
                        },
                        new
                        {
                            Id = 8,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "cw",
                            Pages = 142,
                            Price = 49.950000000000003,
                            PublisherId = 3,
                            Title = "Coding on the Weekend"
                        },
                        new
                        {
                            Id = 9,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "dihw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 2,
                            Title = "Doing it the Hard Way"
                        },
                        new
                        {
                            Id = 10,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "emm",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Excuses to Miss Meetings"
                        },
                        new
                        {
                            Id = 11,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "endw",
                            Pages = 153,
                            Price = 79.950000000000003,
                            PublisherId = 1,
                            Title = "Excuses for Not Writing Documentation"
                        },
                        new
                        {
                            Id = 12,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "ewut",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 2,
                            Title = "Excuses for Not Writing Unit Tests"
                        },
                        new
                        {
                            Id = 13,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "fhcw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 3,
                            Title = "Forgetting How Your Own COde Works"
                        },
                        new
                        {
                            Id = 14,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "galb",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 4,
                            Title = "Getting an Arduino LED to Blink"
                        },
                        new
                        {
                            Id = 15,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "gitw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 5,
                            Title = "Getting it to Work"
                        },
                        new
                        {
                            Id = 16,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "gtem",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 5,
                            Title = "Googling the Error Message"
                        },
                        new
                        {
                            Id = 17,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hldu",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 4,
                            Title = "Hating on Languages You Don't use"
                        },
                        new
                        {
                            Id = 18,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hnhy",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 3,
                            Title = "Hoping Nobody Hacks You"
                        },
                        new
                        {
                            Id = 19,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hoos",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 2,
                            Title = "Hanging out on Slack"
                        },
                        new
                        {
                            Id = 20,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hopc",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Hating Other People's Code"
                        },
                        new
                        {
                            Id = 21,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "htw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Hoping This Works"
                        },
                        new
                        {
                            Id = 22,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "id",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "It Depends"
                        },
                        new
                        {
                            Id = 23,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "msgc",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Memorizing Six Git Commands"
                        },
                        new
                        {
                            Id = 24,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "pbte",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Programming by Trial and Error"
                        },
                        new
                        {
                            Id = 25,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "pkas",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Pretending to Know About Stuff"
                        },
                        new
                        {
                            Id = 26,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "rfsw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Rewriting Your Front End Every Six Weeks"
                        },
                        new
                        {
                            Id = 27,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "sisi",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Solving Imaginary Scaling Issues"
                        },
                        new
                        {
                            Id = 28,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "tcic",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Turning Coffee Into Code"
                        },
                        new
                        {
                            Id = 29,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "tsuw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Trying Stuff Until it Works"
                        },
                        new
                        {
                            Id = 30,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "wcnr",
                            Pages = 121,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Writing Code that Nobody Else Can Read"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PublisherAddressId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublisherAddressId")
                        .IsUnique();

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "Fairview Press",
                            PublisherAddressId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "Harlequin Enterprises Ltd",
                            PublisherAddressId = 2
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "Parragon",
                            PublisherAddressId = 3
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "Barrie & Jenkins",
                            PublisherAddressId = 4
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Name = "Times Books",
                            PublisherAddressId = 5
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.PublisherAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PublisherAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Minneapolis",
                            Country = "USA",
                            Road = "2450 Riverside Avenue South",
                            ZipCode = "55401"
                        },
                        new
                        {
                            Id = 2,
                            City = "Toronto",
                            Country = "CAN",
                            Road = "22 Adelaide Street West",
                            ZipCode = "M5H 4E3"
                        },
                        new
                        {
                            Id = 3,
                            City = "Bath",
                            Country = "ENG",
                            Road = "B-38, Sector 5",
                            ZipCode = "BA2"
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            Country = "ENG",
                            Road = "289 Westbourne Grove",
                            ZipCode = "W11 2QA"
                        },
                        new
                        {
                            Id = 5,
                            City = "New York",
                            Country = "USA",
                            Road = "115 West 18th Street",
                            ZipCode = "10021"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Smith",
                            PasswordHash = new byte[] { 41, 146, 219, 176, 76, 84, 135, 79, 125, 50, 47, 54, 62, 195, 240, 91, 80, 16, 96, 118, 59, 231, 232, 136, 88, 46, 149, 116, 1, 47, 75, 155, 0, 211, 206, 122, 153, 220, 184, 198, 30, 20, 74, 229, 189, 67, 71, 36, 191, 16, 176, 157, 136, 85, 43, 121, 11, 116, 158, 48, 14, 115, 105, 182 },
                            PasswordSalt = new byte[] { 221, 54, 193, 151, 62, 200, 185, 87, 25, 63, 145, 127, 83, 125, 55, 247, 103, 104, 243, 143, 90, 50, 80, 245, 112, 101, 74, 32, 11, 234, 116, 207, 26, 33, 225, 163, 81, 41, 96, 223, 250, 105, 185, 82, 132, 22, 185, 154, 149, 199, 250, 48, 52, 225, 55, 6, 24, 30, 125, 137, 121, 82, 70, 78, 34, 236, 110, 126, 160, 219, 73, 89, 178, 45, 149, 219, 163, 78, 9, 63, 119, 137, 8, 135, 196, 55, 180, 2, 154, 199, 37, 205, 195, 104, 10, 197, 27, 247, 122, 52, 106, 135, 50, 127, 132, 36, 99, 37, 192, 106, 211, 103, 105, 222, 221, 47, 74, 130, 0, 144, 221, 213, 255, 70, 130, 172, 166, 215 },
                            Role = "admin",
                            Username = "john"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ana Boyle",
                            PasswordHash = new byte[] { 93, 184, 198, 108, 125, 79, 137, 215, 9, 56, 210, 70, 85, 177, 71, 166, 123, 193, 59, 121, 237, 120, 111, 181, 20, 243, 219, 243, 153, 5, 90, 193, 67, 219, 200, 77, 60, 251, 227, 19, 14, 241, 153, 230, 34, 95, 249, 46, 254, 103, 30, 61, 111, 190, 49, 121, 202, 160, 9, 27, 171, 208, 113, 79 },
                            PasswordSalt = new byte[] { 28, 209, 118, 158, 60, 161, 140, 201, 31, 191, 125, 166, 93, 219, 54, 189, 61, 169, 98, 6, 44, 15, 91, 157, 82, 145, 57, 167, 120, 71, 255, 230, 171, 212, 233, 124, 25, 128, 35, 203, 247, 245, 164, 117, 5, 135, 78, 227, 241, 103, 97, 154, 88, 255, 97, 108, 111, 130, 45, 29, 23, 228, 124, 221, 139, 219, 117, 51, 242, 82, 114, 104, 155, 47, 204, 78, 216, 98, 203, 180, 75, 84, 40, 3, 79, 157, 103, 10, 50, 86, 252, 225, 141, 84, 208, 132, 143, 32, 14, 5, 73, 243, 94, 139, 254, 31, 93, 6, 1, 180, 39, 42, 28, 238, 93, 159, 72, 161, 200, 149, 154, 208, 247, 15, 226, 163, 219, 205 },
                            Role = "admin",
                            Username = "ana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Antonio Banderas",
                            PasswordHash = new byte[] { 171, 220, 92, 89, 250, 35, 20, 67, 129, 49, 45, 87, 146, 230, 192, 206, 148, 180, 67, 60, 40, 90, 158, 230, 41, 36, 214, 139, 34, 117, 31, 198, 42, 194, 218, 118, 31, 138, 223, 53, 233, 1, 183, 127, 18, 130, 92, 175, 141, 29, 102, 223, 136, 10, 224, 66, 247, 215, 148, 22, 6, 72, 159, 182 },
                            PasswordSalt = new byte[] { 172, 107, 161, 237, 223, 119, 221, 167, 68, 159, 26, 14, 125, 95, 168, 200, 43, 75, 142, 251, 51, 219, 158, 39, 130, 136, 242, 87, 80, 216, 79, 38, 175, 204, 252, 148, 92, 81, 83, 206, 48, 121, 222, 242, 144, 91, 53, 211, 90, 137, 227, 72, 249, 179, 170, 167, 158, 184, 185, 85, 207, 233, 245, 21, 235, 131, 148, 31, 250, 121, 120, 3, 40, 151, 38, 15, 161, 192, 92, 150, 0, 108, 117, 4, 47, 68, 186, 127, 166, 160, 149, 183, 72, 44, 76, 185, 177, 200, 75, 209, 61, 230, 160, 119, 162, 106, 219, 107, 95, 83, 115, 197, 189, 95, 190, 225, 250, 130, 2, 89, 5, 110, 99, 248, 6, 25, 101, 186 },
                            Role = "user",
                            Username = "tony"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Julio Iglesias",
                            PasswordHash = new byte[] { 46, 248, 145, 152, 61, 180, 121, 193, 49, 54, 41, 31, 226, 34, 156, 223, 110, 71, 44, 19, 164, 222, 238, 214, 42, 245, 211, 52, 60, 148, 222, 117, 67, 35, 14, 234, 42, 133, 45, 196, 219, 178, 217, 123, 39, 144, 157, 136, 137, 114, 170, 21, 211, 200, 180, 101, 32, 84, 229, 12, 104, 56, 182, 217 },
                            PasswordSalt = new byte[] { 70, 173, 194, 96, 55, 92, 125, 173, 88, 60, 94, 194, 152, 88, 128, 10, 187, 224, 27, 54, 191, 120, 154, 39, 249, 235, 90, 88, 67, 215, 210, 93, 46, 214, 239, 251, 152, 210, 132, 13, 156, 218, 199, 209, 29, 33, 222, 47, 106, 39, 19, 182, 71, 73, 225, 25, 156, 200, 192, 49, 86, 28, 105, 247, 243, 148, 214, 192, 57, 236, 98, 154, 107, 11, 238, 19, 92, 127, 177, 181, 150, 233, 75, 117, 86, 51, 121, 245, 49, 131, 239, 90, 173, 167, 136, 186, 138, 238, 144, 132, 245, 59, 182, 47, 150, 226, 151, 243, 65, 61, 168, 175, 90, 172, 210, 115, 44, 195, 231, 127, 186, 118, 20, 174, 44, 71, 174, 239 },
                            Role = "user",
                            Username = "julio"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Placido Iglesias",
                            PasswordHash = new byte[] { 120, 179, 248, 19, 23, 97, 152, 28, 135, 26, 58, 184, 67, 124, 152, 85, 154, 190, 156, 107, 176, 75, 187, 193, 189, 81, 247, 87, 0, 226, 8, 230, 191, 81, 64, 201, 207, 183, 48, 239, 96, 142, 198, 219, 112, 106, 78, 5, 193, 230, 14, 148, 218, 74, 87, 84, 235, 122, 199, 141, 228, 165, 63, 85 },
                            PasswordSalt = new byte[] { 18, 214, 72, 182, 37, 168, 80, 22, 109, 136, 104, 93, 7, 214, 171, 133, 175, 73, 26, 236, 161, 204, 71, 21, 90, 24, 237, 247, 90, 94, 189, 2, 12, 81, 40, 146, 141, 104, 85, 244, 246, 34, 119, 158, 150, 247, 145, 109, 18, 139, 54, 17, 153, 190, 196, 92, 70, 94, 52, 79, 198, 56, 120, 191, 255, 167, 161, 1, 160, 246, 131, 32, 140, 11, 27, 76, 212, 30, 125, 225, 92, 122, 210, 191, 103, 157, 76, 188, 144, 145, 48, 41, 168, 134, 45, 120, 147, 221, 17, 101, 4, 60, 183, 121, 0, 166, 4, 109, 206, 42, 109, 236, 240, 78, 211, 53, 211, 146, 92, 94, 68, 153, 208, 44, 172, 91, 192, 50 },
                            Role = "user",
                            Username = "place"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.AuthorBook", b =>
                {
                    b.HasOne("MyWebAPICore.Models.Author", "Author")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebAPICore.Models.Book", "Book")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Book", b =>
                {
                    b.HasOne("MyWebAPICore.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Publisher", b =>
                {
                    b.HasOne("MyWebAPICore.Models.PublisherAddress", "PublisherAddress")
                        .WithOne("Publisher")
                        .HasForeignKey("MyWebAPICore.Models.Publisher", "PublisherAddressId");

                    b.Navigation("PublisherAddress");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Author", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Book", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("MyWebAPICore.Models.PublisherAddress", b =>
                {
                    b.Navigation("Publisher")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
