// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPICore.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWebAPICore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220225092210_SomeChanges")]
    partial class SomeChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyWebAPICore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1950, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "cloehopper@school.com",
                            Image = "cloehopper",
                            Name = "Cloe Hopper"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1955, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "davidremnick@school.com",
                            Image = "davidremnick",
                            Name = "David Remnick"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1967, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "joannakavena@gmail.com",
                            Image = "joannakavena",
                            Name = "Joanna Kavena"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1912, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "johncheever@school.com",
                            Image = "johncheever",
                            Name = "John Cheever"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1980, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "joshuacohen@school.com",
                            Image = "joshuacohen",
                            Name = "Joshua Cohen"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1971, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "patrickness@school.com",
                            Image = "patrickness",
                            Name = "Patrick Ness"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1975, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "rebeccaswift@school.com",
                            Image = "rebeccaswift",
                            Name = "Rebecca Swift"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1979, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "sarahperry@school.com",
                            Image = "sarahperry",
                            Name = "Sarah Perry"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1948, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "simonmawer@school.com",
                            Image = "simonmawer",
                            Name = "Simon Mawer"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Australian author Chloe Hooper, 39, is creating a singularly diverse literary career. Her 2002 debut novel, A Child's Book of True Crime, made the Orange prize shortlist, while The Tall Man (2009), a nonfiction investigation into the death of an Aboriginal man in police custody, earned praise from Philip Roth and Peter Carey. Her new novel is a gothic thriller, The Engagement.",
                            Birthday = new DateTime(1960, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "tomwinton@school.com",
                            Image = "tomwinton",
                            Name = "Tom Winton"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.AuthorBook", b =>
                {
                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("BookId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("AuthorBooks");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 7
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 11
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 24
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 28
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 9
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 11
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 19
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 29
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 4
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 12
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 21
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 26
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 15
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 22
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 27
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 2
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 8
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 10
                        },
                        new
                        {
                            AuthorId = 6,
                            BookId = 17
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 1
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 5
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 23
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 30
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 3
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 13
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 14
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 17
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 18
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 25
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 29
                        },
                        new
                        {
                            AuthorId = 10,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 10,
                            BookId = 20
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "bjsf",
                            Pages = 171,
                            Price = 79.950000000000003,
                            PublisherId = 1,
                            Title = "Bloated JabbaScript Frameworks"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "bta",
                            Pages = 158,
                            Price = 79.950000000000003,
                            PublisherId = 2,
                            Title = "Blaming the Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "btog",
                            Pages = 111,
                            Price = 69.950000000000003,
                            PublisherId = 3,
                            Title = "Blame the Other Guy"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "btu",
                            Pages = 152,
                            Price = 69.950000000000003,
                            PublisherId = 4,
                            Title = "Blaming the User"
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "coft",
                            Pages = 166,
                            Price = 69.950000000000003,
                            PublisherId = 5,
                            Title = "Commenting Out Failed Tests"
                        },
                        new
                        {
                            Id = 6,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "cpso",
                            Pages = 159,
                            Price = 69.950000000000003,
                            PublisherId = 5,
                            Title = "Copying and Pasting from Stack Overflow"
                        },
                        new
                        {
                            Id = 7,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "cswh",
                            Pages = 129,
                            Price = 59.950000000000003,
                            PublisherId = 4,
                            Title = "Changing Stuff and Seeing What Happens"
                        },
                        new
                        {
                            Id = 8,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "cw",
                            Pages = 142,
                            Price = 49.950000000000003,
                            PublisherId = 3,
                            Title = "Coding on the Weekend"
                        },
                        new
                        {
                            Id = 9,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "dihw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 2,
                            Title = "Doing it the Hard Way"
                        },
                        new
                        {
                            Id = 10,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "emm",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Excuses to Miss Meetings"
                        },
                        new
                        {
                            Id = 11,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "endw",
                            Pages = 153,
                            Price = 79.950000000000003,
                            PublisherId = 1,
                            Title = "Excuses for Not Writing Documentation"
                        },
                        new
                        {
                            Id = 12,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "ewut",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 2,
                            Title = "Excuses for Not Writing Unit Tests"
                        },
                        new
                        {
                            Id = 13,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "fhcw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 3,
                            Title = "Forgetting How Your Own COde Works"
                        },
                        new
                        {
                            Id = 14,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "galb",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 4,
                            Title = "Getting an Arduino LED to Blink"
                        },
                        new
                        {
                            Id = 15,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "gitw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 5,
                            Title = "Getting it to Work"
                        },
                        new
                        {
                            Id = 16,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "gtem",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 5,
                            Title = "Googling the Error Message"
                        },
                        new
                        {
                            Id = 17,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hldu",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 4,
                            Title = "Hating on Languages You Don't use"
                        },
                        new
                        {
                            Id = 18,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hnhy",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 3,
                            Title = "Hoping Nobody Hacks You"
                        },
                        new
                        {
                            Id = 19,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hoos",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 2,
                            Title = "Hanging out on Slack"
                        },
                        new
                        {
                            Id = 20,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "hopc",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Hating Other People's Code"
                        },
                        new
                        {
                            Id = 21,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "htw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Hoping This Works"
                        },
                        new
                        {
                            Id = 22,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "id",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "It Depends"
                        },
                        new
                        {
                            Id = 23,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "msgc",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Memorizing Six Git Commands"
                        },
                        new
                        {
                            Id = 24,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "pbte",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Programming by Trial and Error"
                        },
                        new
                        {
                            Id = 25,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "pkas",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Pretending to Know About Stuff"
                        },
                        new
                        {
                            Id = 26,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "rfsw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Rewriting Your Front End Every Six Weeks"
                        },
                        new
                        {
                            Id = 27,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "sisi",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Solving Imaginary Scaling Issues"
                        },
                        new
                        {
                            Id = 28,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "tcic",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Turning Coffee Into Code"
                        },
                        new
                        {
                            Id = 29,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "tsuw",
                            Pages = 113,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Trying Stuff Until it Works"
                        },
                        new
                        {
                            Id = 30,
                            Deleted = false,
                            Description = "Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap. Its amazing how loading a single webpage can cost you upwards of ~5MB. I think the average web page size is 3MB right now, I remember reading that somewhere, dont remember where though.<br>Might not matter when using wifi, but thats a whole 1% of my monthly cell data. 100 pages a month and im done. All of this for what? Usually some annoying animations, or other overengineered crap",
                            Image = "wcnr",
                            Pages = 121,
                            Price = 59.950000000000003,
                            PublisherId = 1,
                            Title = "Writing Code that Nobody Else Can Read"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PublisherAddressId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublisherAddressId")
                        .IsUnique();

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "Fairview Press",
                            PublisherAddressId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "Harlequin Enterprises Ltd",
                            PublisherAddressId = 2
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "Parragon",
                            PublisherAddressId = 3
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "Barrie & Jenkins",
                            PublisherAddressId = 4
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Name = "Times Books",
                            PublisherAddressId = 5
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.PublisherAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PublisherAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Minneapolis",
                            Country = "USA",
                            Road = "2450 Riverside Avenue South",
                            ZipCode = "55401"
                        },
                        new
                        {
                            Id = 2,
                            City = "Toronto",
                            Country = "CAN",
                            Road = "22 Adelaide Street West",
                            ZipCode = "M5H 4E3"
                        },
                        new
                        {
                            Id = 3,
                            City = "Bath",
                            Country = "ENG",
                            Road = "B-38, Sector 5",
                            ZipCode = "BA2"
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            Country = "ENG",
                            Road = "289 Westbourne Grove",
                            ZipCode = "W11 2QA"
                        },
                        new
                        {
                            Id = 5,
                            City = "New York",
                            Country = "USA",
                            Road = "115 West 18th Street",
                            ZipCode = "10021"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Smith",
                            PasswordHash = new byte[] { 148, 223, 219, 182, 0, 134, 202, 197, 236, 246, 33, 138, 87, 253, 170, 166, 65, 93, 32, 36, 193, 194, 244, 14, 2, 194, 102, 150, 26, 90, 1, 236, 171, 163, 179, 21, 61, 49, 89, 197, 186, 169, 153, 7, 142, 133, 32, 18, 179, 160, 78, 205, 210, 59, 134, 184, 173, 112, 226, 24, 174, 168, 77, 208 },
                            PasswordSalt = new byte[] { 59, 146, 38, 120, 139, 73, 85, 254, 6, 107, 148, 94, 221, 124, 167, 30, 63, 40, 122, 223, 95, 226, 31, 4, 171, 238, 175, 84, 48, 160, 160, 193, 184, 181, 41, 120, 225, 250, 191, 117, 90, 78, 242, 77, 1, 43, 188, 69, 127, 177, 191, 178, 212, 216, 214, 83, 141, 97, 208, 224, 201, 121, 85, 154, 214, 49, 233, 5, 80, 173, 61, 227, 235, 235, 41, 201, 219, 42, 78, 21, 105, 178, 125, 12, 243, 26, 32, 10, 37, 57, 193, 240, 127, 194, 207, 96, 210, 33, 49, 245, 134, 58, 63, 60, 82, 163, 214, 148, 95, 228, 96, 205, 153, 51, 12, 249, 152, 170, 255, 178, 15, 58, 76, 137, 70, 157, 74, 213 },
                            Role = "admin",
                            Username = "john"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ana Boyle",
                            PasswordHash = new byte[] { 14, 23, 239, 79, 66, 91, 22, 89, 162, 217, 86, 149, 218, 106, 142, 229, 79, 216, 13, 118, 0, 106, 53, 222, 217, 222, 215, 88, 60, 173, 53, 109, 149, 105, 31, 97, 27, 90, 227, 42, 252, 6, 74, 139, 155, 12, 39, 92, 154, 79, 236, 118, 168, 88, 83, 147, 102, 248, 209, 132, 151, 160, 0, 178 },
                            PasswordSalt = new byte[] { 33, 74, 55, 60, 132, 53, 25, 35, 69, 37, 17, 138, 7, 235, 14, 90, 61, 183, 6, 88, 5, 94, 99, 241, 63, 206, 248, 162, 208, 10, 40, 42, 49, 13, 106, 243, 96, 37, 108, 53, 86, 154, 125, 85, 90, 190, 220, 245, 113, 110, 57, 0, 225, 99, 109, 198, 123, 57, 136, 143, 250, 237, 234, 64, 71, 140, 195, 228, 81, 148, 22, 34, 253, 233, 8, 146, 89, 134, 78, 88, 49, 119, 90, 16, 135, 200, 200, 238, 113, 43, 98, 223, 78, 50, 152, 250, 27, 194, 188, 127, 67, 15, 145, 49, 189, 147, 223, 99, 81, 106, 190, 65, 72, 244, 68, 238, 247, 162, 123, 117, 11, 24, 172, 253, 94, 204, 129, 133 },
                            Role = "admin",
                            Username = "ana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Antonio Banderas",
                            PasswordHash = new byte[] { 1, 197, 179, 204, 146, 246, 60, 61, 64, 169, 249, 62, 115, 235, 77, 126, 248, 80, 11, 226, 83, 130, 46, 135, 71, 101, 194, 235, 32, 239, 146, 225, 43, 49, 100, 229, 79, 146, 253, 6, 11, 105, 138, 49, 51, 73, 252, 236, 173, 71, 65, 164, 234, 189, 159, 253, 148, 227, 67, 105, 100, 5, 57, 5 },
                            PasswordSalt = new byte[] { 12, 103, 155, 61, 59, 201, 90, 199, 151, 207, 149, 6, 210, 249, 239, 5, 150, 233, 202, 19, 221, 105, 90, 74, 132, 140, 211, 209, 196, 116, 17, 209, 19, 181, 235, 9, 41, 102, 32, 72, 124, 215, 112, 32, 134, 48, 51, 225, 239, 137, 86, 20, 7, 246, 69, 252, 236, 15, 199, 241, 141, 221, 121, 188, 13, 46, 118, 94, 124, 175, 27, 196, 225, 183, 217, 196, 113, 170, 163, 27, 86, 81, 73, 15, 36, 174, 63, 26, 66, 68, 109, 106, 154, 205, 175, 118, 150, 71, 143, 140, 138, 118, 94, 30, 85, 58, 200, 250, 22, 128, 193, 75, 31, 210, 126, 139, 10, 219, 97, 29, 150, 168, 123, 196, 53, 70, 109, 113 },
                            Role = "user",
                            Username = "tony"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Julio Iglesias",
                            PasswordHash = new byte[] { 166, 246, 122, 230, 57, 2, 122, 4, 190, 198, 226, 237, 14, 51, 234, 93, 20, 154, 196, 157, 128, 127, 236, 245, 87, 30, 246, 204, 93, 167, 127, 225, 67, 182, 158, 221, 84, 126, 248, 207, 28, 252, 85, 246, 123, 45, 145, 12, 170, 47, 252, 57, 255, 34, 67, 208, 2, 171, 169, 114, 112, 150, 187, 153 },
                            PasswordSalt = new byte[] { 30, 19, 49, 175, 217, 70, 204, 119, 148, 50, 86, 49, 121, 255, 170, 40, 171, 70, 204, 45, 133, 223, 18, 147, 201, 13, 113, 34, 186, 120, 203, 47, 140, 71, 207, 159, 97, 253, 175, 253, 4, 104, 138, 16, 179, 72, 54, 17, 10, 227, 63, 0, 33, 176, 86, 50, 140, 184, 30, 161, 11, 18, 57, 74, 6, 180, 53, 138, 124, 191, 184, 246, 80, 35, 100, 33, 188, 164, 234, 21, 100, 175, 50, 105, 48, 60, 125, 107, 14, 76, 75, 73, 42, 99, 60, 252, 84, 14, 147, 189, 80, 194, 250, 44, 207, 215, 135, 120, 159, 155, 250, 122, 252, 156, 17, 226, 114, 203, 45, 115, 35, 196, 51, 201, 113, 165, 114, 177 },
                            Role = "user",
                            Username = "julio"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Placido Iglesias",
                            PasswordHash = new byte[] { 195, 49, 173, 51, 49, 140, 218, 108, 64, 24, 163, 179, 214, 59, 202, 4, 31, 52, 221, 149, 168, 250, 85, 244, 75, 41, 195, 89, 250, 55, 189, 42, 240, 232, 239, 87, 63, 142, 43, 211, 14, 111, 73, 112, 105, 45, 197, 94, 211, 202, 233, 214, 80, 22, 118, 75, 197, 76, 30, 209, 192, 193, 181, 174 },
                            PasswordSalt = new byte[] { 176, 106, 96, 89, 229, 254, 99, 107, 139, 249, 227, 29, 194, 221, 60, 213, 232, 137, 38, 103, 88, 195, 142, 3, 45, 89, 122, 218, 204, 203, 17, 26, 92, 17, 195, 217, 168, 72, 105, 129, 92, 87, 199, 162, 211, 182, 193, 5, 77, 76, 228, 236, 30, 141, 6, 194, 195, 167, 149, 47, 202, 200, 144, 65, 90, 220, 197, 142, 74, 96, 217, 239, 192, 230, 94, 116, 194, 110, 52, 35, 146, 129, 217, 206, 58, 134, 71, 126, 96, 142, 194, 82, 48, 107, 187, 119, 45, 241, 92, 167, 12, 108, 34, 29, 203, 103, 70, 63, 25, 200, 26, 212, 234, 117, 139, 14, 54, 93, 25, 129, 95, 118, 139, 254, 42, 220, 130, 163 },
                            Role = "user",
                            Username = "place"
                        });
                });

            modelBuilder.Entity("MyWebAPICore.Models.AuthorBook", b =>
                {
                    b.HasOne("MyWebAPICore.Models.Author", "Author")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebAPICore.Models.Book", "Book")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Book", b =>
                {
                    b.HasOne("MyWebAPICore.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Publisher", b =>
                {
                    b.HasOne("MyWebAPICore.Models.PublisherAddress", "PublisherAddress")
                        .WithOne("Publisher")
                        .HasForeignKey("MyWebAPICore.Models.Publisher", "PublisherAddressId");

                    b.Navigation("PublisherAddress");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Author", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("MyWebAPICore.Models.Book", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("MyWebAPICore.Models.PublisherAddress", b =>
                {
                    b.Navigation("Publisher")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
